[MIG] account_invoice_margin_sale_delivered_sync: Migration to 13.0
OCA/margin-analysis pull request #119
Opened 2021-10-26 14:26 UTC by chienandalu

Keep purchase price delivered between sale order line and invoice lines

cc @Tecnativa TT32680

ping @sergio-teruel @carlosdauden

2021-10-26 18:55 UTC, sergio-teruel requested changes

2021-10-26 18:55 UTC, sergio-teruel commented on account_invoice_margin_sale_delivered_sync/models/account_move.py
> +    )
@chienandalu remove the inverse attribute

2021-10-26 18:55 UTC, sergio-teruel commented
Travis fails

2021-11-03 11:40 UTC, chienandalu commented on account_invoice_margin_sale_delivered_sync/models/account_move.py
> +    )
:+1:

2021-11-03 17:01 UTC, chienandalu commented
Travis green at last

2021-11-09 09:04 UTC, sergio-teruel approved these changes

2021-11-09 11:51 UTC, carlosdauden approved these changes

2021-11-09 12:56 UTC, pedrobaeza commented
/ocabot merge patch

2021-11-09 15:18 UTC, merged