[16.0][MIG] sale_margin_delivered
OCA/margin-analysis pull request #176
Opened 2023-06-05 13:24 UTC by aliciagaarzo

Migration of **sale_margin_delivered** module to version 16

2023-06-06 11:31 UTC, aliciagaarzo commented
Waiting for module migration **sale_margin_security** https://github.com/OCA/margin-analysis/pull/173

2023-06-07 11:32 UTC, rousseldenis commented
/ocabot migration sale_margin_delivered

2023-06-08 00:20 UTC, pedrobaeza commented
/ocabot migration sale_margin_delivered

2023-06-22 10:39 UTC, HugoCordobaLeal commented on sale_margin_delivered/views/sale_margin_delivered_view.xml
> -            eval="[(4,ref('sale_margin_security.group_sale_margin_security'))]"
#173 is already merged, can you add this again?

2023-08-09 06:43 UTC, dreispt approved these changes

2023-08-09 14:00 UTC, fcvalgar approved these changes
Functional review.
LGTM, thank you @aliciagaarzo 👍

![image](https://github.com/OCA/margin-analysis/assets/17847432/dfa4034c-2dfe-4a1a-9401-966be2ceed48)


![image](https://github.com/OCA/margin-analysis/assets/17847432/2fbfbd41-46ab-4380-b29e-8694a97db4bb)

2023-08-09 14:33 UTC, fcvalgar requested changes
@aliciagaarzo I think the fields are displayed even if you do not have Show Sale Margin permissions.

![Captura desde 2023-08-09 16-33-21](https://github.com/OCA/margin-analysis/assets/17847432/8028b26e-124b-41ec-86de-deb6373b8e38)

@moduon MT-3399

2023-08-31 17:38 UTC, rafaelbn commented
Hello @sergio-teruel @chienandalu @CarlosRoca13 , do you want to review before merging as maintainers and contributors? Thank you!

2023-08-31 17:38 UTC, rafaelbn commented
/ocabot rebase

2023-09-01 05:53 UTC, chienandalu requested changes
Hi @aliciagaarzo thanks for you work.

Some comments bellow :)

cc @Tecnativa TT44880

2023-09-01 05:53 UTC, chienandalu commented on sale_margin_delivered/views/sale_margin_delivered_view.xml
> -        />
You have to add the groups to fields themselves. Not just removing them from the view.

2023-09-01 05:53 UTC, chienandalu commented on sale_margin_delivered/reports/sale_report.py
> +        return res
This one's a little picky, but more in line with the previous nomenclature
```suggestion
        fields = super()._select_additional_fields()
        fields[
            "margin_delivered"
        ] = "SUM(l.margin_delivered / COALESCE(s.currency_rate, 1.0))"
        return fields
```

2023-09-01 05:53 UTC, chienandalu commented on sale_margin_delivered/reports/sale_report.py
> +        ] = "SUM(l.margin_delivered / COALESCE(s.currency_rate, 1.0))"
Follow the guideline for currency conversion in reports: https://github.com/odoo/odoo/blame/116322b705c96a6f23167d09c8f42b569a9e6f22/addons/sale_margin/report/sale_report.py#L15-L16

2023-09-05 09:05 UTC, sergio-teruel commented
Ping @aliciagaarzo Can you anttend pending comments. Thanks

2023-09-12 08:43 UTC, pilarvargas-tecnativa commented
Superseed by: https://github.com/OCA/margin-analysis/pull/183

2023-09-12 20:53 UTC, closed without merging