[IMP] sale_margin_security: Allows more flexibility in groups
OCA/margin-analysis pull request #223
Opened 2024-12-11 10:18 UTC by rousseldenis

As in some flows, people want to split fields visibility to buyers and salesmen, restore the margin group. As in cost module, there is two groups, add a group for sale margins + edit costs

2024-12-12 07:57 UTC, lmignon approved these changes
Granular security is easier to manage.... Thank you @rousseldenis

2024-12-12 08:10 UTC, sergio-teruel approved these changes

2024-12-12 08:36 UTC, rousseldenis commented
@OCA/accounting-maintainers Could you link this to :

https://github.com/OCA/margin-analysis/issues/222

Thanks

2024-12-16 10:33 UTC, yajo requested changes
In https://github.com/OCA/margin-analysis/issues/222, we already touched upon this matter. From my perspective, this approach seems to undermine the intended security, as it effectively turns the security into a placebo. Anyone with access to margin will essentially have access to costs, which, in practical terms, means the same thing.

In the previous PRs from https://github.com/OCA/product-attribute/pull/1538#issue-2171562830 and https://github.com/OCA/margin-analysis/pull/198#issue-2175629776, we addressed the inconsistencies and security issues that made the previous status difficult to manage effectively. Thanks to those contributions, the UX has significantly improved, and we now have a simple, intuitive permissions dropdown:

![image](https://github.com/user-attachments/assets/7f4a6837-2027-4c7a-a842-cd8a0aa77bed)

This solution made security clear and functional right out of the box, which I believe was a positive step forward.

If we were to merge this new approach, however, we would return to the need for debug mode to configure security permissions, which could lead to inconsistent states. For example, here are some instances from Runboat:

![image](https://github.com/user-attachments/assets/e5622c4a-4dac-4af1-9a50-6310fe3e1fbd)

![image](https://github.com/user-attachments/assets/e58fb72c-1dca-403e-b94d-ac1034332402)

By contrast, I think the thorough functional validation done by @Gelojr in https://github.com/OCA/margin-analysis/pull/198#pullrequestreview-1951828542 demonstrates how the current approach ensures consistent behavior across the board.

That said, I still can see that adding an intermediate permission option to the dropdown could be a valuable enhancement, and it could look like this:

1. Read.
2. Edit only in SO.
3. Edit.

I understand there could be use cases where you might want salespeople to edit costs in the SO but not in the product. However, beyond this point, I believe adding more complexity would only lead to confusion and potential misconfigurations, without genuinely improving the system. For that reason, I don't agree with the proposed change in its current form.

In the end, my concern is that increasing complexity may not make the system easier to manage, but rather more prone to mistakes and misconfigurations.

2024-12-17 19:41 UTC, rafaelbn reviewed
Hello! 😄 

We would appreciate your concerns about maintaining flexibility without adding unnecessary complexity or creating a false sense of security. The key challenge is to offer more granular visibility options without making the configuration confusing or difficult to manage.

How do you think we could achieve this balance? For example, introduce the new permission level that give teams the control they need—without requiring debug mode or hidden configurations—while still keeping the user experience clear and straightforward?

The tooltip could be clear to explain the groups so our users don't mistake with them.

I’d really value your input on how to simplify and adapt these settings to better serve everyone’s needs.

I agree with @yajo , and also I can understand that something that for us our our clients don't have any sense for other have it. The goal is to fit everyone.

Thank you! ❤️

2024-12-18 13:19 UTC, rousseldenis commented
Hi,

I didn't see the category in groups configuration.

I will add the category and configuration will show:

![image](https://github.com/user-attachments/assets/3ac1e7f3-e6a9-4ab9-a740-966d3e1f1f80)

2024-12-18 13:22 UTC, rousseldenis commented
@rafaelbn If I understand, your main concern is about user interface. And I understand it. We usually minimize the impact of configuration at that level (using base_user_role module or letting the administrator manages it by itself). :sweat_smile:

2024-12-18 13:27 UTC, rousseldenis commented
> I understand there could be use cases where you might want salespeople to edit costs in the SO but not in the product.

That's not our use case. The reason of that change is about margin visibility (and I know costs people can compute them).

People that could have access to costs could not necessarily have access (direct) to margins.

2024-12-18 17:01 UTC, rousseldenis commented
@rafaelbn The problem to dsiplay a selection is that the groups are not strictly hierarchical.

2024-12-20 08:09 UTC, yajo commented
Indeed. Let's try to get to something more usable and sensible.

Only the costs fields are actually editable, because margins are computed, right? So, the edit mode on margins would make no sense IMHO.

Option A, if you want to split displaying or hiding margins, is to divide between a dropdown and a checkbox. Something like this:

![Diagrama sin título drawio](https://github.com/user-attachments/assets/2f4c7ae5-9b86-4a5d-9b37-5b5ce41df993)


However, IMHO it also doesn't make sense to let somebody actually *edit* the costs without being able to *read* the margins. If you have edit permissions, then I can imagine that you need to know the margin to be able to edit the cost appropriately, right? If so, this Option B would fit better:

![Diagrama sin título drawio (1)](https://github.com/user-attachments/assets/30fc5a6f-9a76-478d-b094-6e7595d50253)


As you can see, both designs feature a warning when the user is creating an inconsistency. This module is suffixed `_security` for a reason, and by allowing only one of the 2 read levels, you are only hiding the information, not blocking it. Thus it's important that the admin gets that warning clearly displayed.

WDYT?

2025-01-02 15:58 UTC, jdidderen-nsi approved these changes
I understand the changes and i don't think it hurts anyone to have it.
I agree in principle that having access to the cost gives an idea of the margin. 
However, I don't see the issue with the approach proposed by Denis, as the old approach is still possible and the two can co-exist.

For the UX debate, can we simply have the following ?
![image](https://github.com/user-attachments/assets/8e5ba90a-a899-44c9-81c0-aaa4bb8b559f)
![image](https://github.com/user-attachments/assets/30616d5e-9222-47bb-bb25-47fa0b115613)
![image](https://github.com/user-attachments/assets/b801801a-ff84-4fe2-acff-c7f039444e8a)

2025-01-03 07:26 UTC, yajo commented
IIUC https://github.com/OCA/margin-analysis/pull/223#pullrequestreview-2527818423, your proposal is 4 levels of permissions, each one inheriting the previous one:
1. Nothing.
2. Read costs.
3. Read costs and margin.
4. Edit costs and margin.

Is that correct? Would that be good for you @rousseldenis?

2025-01-03 13:50 UTC, jdidderen-nsi commented
> IIUC [#223 (review)](https://github.com/OCA/margin-analysis/pull/223#pullrequestreview-2527818423), your proposal is 4 levels of permissions, each one inheriting the previous one:
> 
> 1. Nothing.
> 2. Read costs.
> 3. Read costs and margin.
> 4. Edit costs and margin.
> 
> Is that correct? Would that be good for you @rousseldenis?

Three module categories : 
- Cost Security (new one)
   - Product Costs (existing one)
   - Sale Margins (new one)

Security groups :
- Product Costs
   - Read (existing one)
   - Edit (existing one)
- Sale Margins
   - Show sale margin (new one)

And the new group has a inherit (implied_ids) on the read security group from product costs. 

The edit security group from product costs is isolated and managed manually.

2025-01-13 11:00 UTC, yajo commented
Could you please explain to me why would somebody be able to edit costs and yet forbidden to see the margin? Isn't that essential information while editing costs? 🤔

2025-01-19 19:10 UTC, rafaelbn commented
Hello all,

What I talked with @rousseldenis in a Google Meet was this result:

![imagen](https://github.com/user-attachments/assets/dbc4a66e-8eb7-4296-af6d-242a9fe181ee)

Best regards 😄 🙏🏼 ❤️ 

@moduon MT-8486

2025-05-13 12:59 UTC, rousseldenis commented
> Hello all,
> 
> What I talked with @rousseldenis in a Google Meet was this result:
> 
> ![imagen](https://private-user-images.githubusercontent.com/8736623/404688489-dbc4a66e-8eb7-4296-af6d-242a9fe181ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDcxNDEyOTUsIm5iZiI6MTc0NzE0MDk5NSwicGF0aCI6Ii84NzM2NjIzLzQwNDY4ODQ4OS1kYmM0YTY2ZS04ZWI3LTQyOTYtYWY2ZC0yNDJhOWZlMTgxZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MTNUMTI1NjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2RiMGJiYTc0NzdjY2FmMjMzYzBlNTNiMDdjNmRiZmRkMjEwYmE5YzUxNGRlZDhhMzU0YTZhNDIyNTE1ODBhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ulRLkgy03JuSkL9sXEH-TSaewe7ipSRIBX-VWiWNoYQ)
> 
> Best regards 😄 🙏🏼 ❤️
> 
> @moduon MT-8486

I finally reverted as the yellow line case is not possible as groups should imply the preceding to be shown as select box.

 @yajo @rafaelbn IMHO, if you want to get the margin access and costs in one operation, you should think about using `base_user_role` module.

2025-05-13 13:02 UTC, rousseldenis commented
At this time, the groups are managed like this:

![image](https://github.com/user-attachments/assets/96ff22a4-cf1c-4c29-bb32-ef1cb422643e)

like suggested

2025-05-14 07:04 UTC, lmignon approved these changes

2025-05-20 06:54 UTC, yajo requested changes
Thanks for the update!

I see that you're finally implementing option A from https://github.com/OCA/margin-analysis/pull/223#issuecomment-2556487578.

I still miss the warning when somebody selects read-only permissions only on either costs or margins. We should make it clear to the sysadmin that the user can compute the other thing easily with a calculator. We're managing user security here, and even if we might trick the user, we shouldn't trick the sysadmin. As a very minimum fix, it should be in the readme.

There's also a bug IIUC, noted below.

2025-05-20 06:54 UTC, yajo commented on sale_margin_security/models/sale_order.py
> +    _inherit = ["sale.order"]
issue: undo this change please. Otherwise, users with read-only permissions for cost will actually be able to write the fields.

2025-05-21 10:53 UTC, rousseldenis commented on sale_margin_security/models/sale_order.py
> +    _inherit = ["sale.order"]
I'll check that

2025-05-21 11:14 UTC, rousseldenis commented on sale_margin_security/models/sale_order.py
> +    _inherit = ["sale.order"]
@yajo In this case, sale order has no field that should be protected by cost group, correct? Only lines should (as it is still now)

2025-05-22 07:12 UTC, yajo commented on sale_margin_security/models/sale_order.py
> +    _inherit = ["sale.order"]
Ah! you're totally right.

2025-10-26 12:40 UTC, closed without merging