[12.0][MIG] account_invoice_margin_sale: Migration to 12.0
OCA/margin-analysis pull request #65
Opened 2019-12-04 11:40 UTC by carlosdauden

@Tecnativa
TT20159

2019-12-04 13:06 UTC, carlosdauden commented
Depends https://github.com/OCA/margin-analysis/pull/66

2019-12-09 22:47 UTC, pedrobaeza commented
Please rebase now that the dependency is merged.

2019-12-10 09:43 UTC, sergio-teruel reviewed
Waiting for green ci

2019-12-10 12:32 UTC, pedrobaeza approved these changes

2019-12-10 12:32 UTC, pedrobaeza commented on account_invoice_margin_sale/__manifest__.py
> +    'development_status': 'Production/Stable',
When promoting to stable, you have to add at least one maintainer

2019-12-10 15:33 UTC, sergio-teruel requested changes

2019-12-10 15:33 UTC, sergio-teruel commented on account_invoice_margin_sale/tests/test_account_invoice_margin_sale.py
> +            'pricelist_id': cls.env.ref('product.list0').id,
Please use a new pricelist to avoid conflicts with other module tests

2019-12-11 15:36 UTC, carlosdauden commented
Changes done

2019-12-11 15:49 UTC, pedrobaeza commented
@sergio-teruel do you approve it?

2019-12-12 14:46 UTC, sergio-teruel approved these changes

2019-12-12 14:47 UTC, pedrobaeza commented
/ocabot merge

2019-12-12 15:13 UTC, merged