[WIP][MIG][13.0] account_invoice_margin: Migration to v13.0
OCA/margin-analysis pull request #72
Opened 2020-02-22 20:24 UTC by sergio-teruel

TT21603

2020-02-24 10:25 UTC, legalsylvain requested changes
Hi @sergio-teruel. Thanks a lot for porting this module.

regarding the port from 12.0 to 13.0 : Code review / no test. :+1: Thanks.

regarding this module, I have a recurring problem with the design of this module, as it bases the computation of the margin of the invoice on all the invoice lines. In fact, some product (and so some lines) should not impact the margin computation. A typical exemple is for "Down Payment"

**Step to reproduce :**
- create a sale order with saleable product.
- create an invoice (A) with a down Payment.
- Create an invoice (B) with the rest of the order to invoice.

![image](https://user-images.githubusercontent.com/3407482/75145209-cda14d80-56f8-11ea-807e-2b49071327c5.png)


**Current result**
the margin of the invoice B has an incorrect margin, specially the percent value.

**Desired result**
- the margin of the invoice B should be based on the product line, and not on the Down Payment line

**What I propose**
- add a boolean ``impact_margin`` on the ``product.template`` / ``product.product`` models, (``default=True``)
- filter the computation of the margin on invoice lines with product with ``impact_margin`` to True.
- Do not display margin and margin_percent on invoice line for product with ``impact_margin`` to False.

1) are you agree with the limitation of this module, regarding Down Payment ? (and certainly other kind of products)
2) If yes, are you agree for the design I propose ?
3) If yes, I can make a PR against your PR, if you want.

kind regards.

2020-03-26 16:18 UTC, manuelcalerosolis approved these changes

2020-03-26 16:18 UTC, manuelcalerosolis commented on account_invoice_margin/security/account_invoice_margin_security.xml
> +<openerp>
<odoo>

2020-03-26 16:18 UTC, manuelcalerosolis commented on account_invoice_margin/security/account_invoice_margin_security.xml
> +<openerp>
Code and functional review.

2020-03-26 16:35 UTC, pedrobaeza commented
@sergio-teruel please check @legalsylvain comments and replace some obsolete `<openerp>` tags.

2020-03-26 19:25 UTC, sergio-teruel commented
@legalsylvain Hi, you are right with the margin behavior for invoices with deposit payments...
mybe we could excluded down payment product for margin computation...How about it?

2020-03-26 19:29 UTC, sergio-teruel commented
@pedrobaeza Changes done

2020-03-26 19:31 UTC, sergio-teruel commented
@legalsylvain About your proposal, I agree.. so if you prefer this option perfect... I am thinking that theese alow to change down payment product ... 
You can make a PR to my PR.... :smile:

2020-03-26 20:24 UTC, sergio-teruel commented
@legalsylvain Can you review last commit to exclude downpayment lines ??

2020-04-16 18:33 UTC, Tardo approved these changes
:+1: Code review, only non-blocking comments

2020-04-16 18:33 UTC, Tardo commented on account_invoice_margin/models/__init__.py
> +# © 2017 Sergio Teruel <sergio.teruel@tecnativa.com>
```suggestion
# Copyright 2017 Sergio Teruel <sergio.teruel@tecnativa.com>
```

2020-04-16 18:33 UTC, Tardo commented on account_invoice_margin/models/account_invoice.py
> +# © 2017 Sergio Teruel <sergio.teruel@tecnativa.com>
```suggestion
# Copyright 2017 Sergio Teruel <sergio.teruel@tecnativa.com>
```

2020-04-16 18:52 UTC, sergio-teruel commented
@Tardo Changes done

2020-04-16 19:07 UTC, pedrobaeza commented
@legalsylvain everything OK in your part?

2020-07-17 08:04 UTC, sergio-teruel commented
Anybody can merge??

2020-07-17 08:51 UTC, pedrobaeza commented
/ocabot merge nobump

2020-07-17 09:34 UTC, merged