[FIX] stored field should not depend on none stored field
OCA/margin-analysis pull request #84
Opened 2020-10-14 20:56 UTC by sebastienbeau

if a stored field depend on a non stored field, really weird behaviour
can occure.
Indeed none-stored field can not be searched correctly and the ORM will
return all product (with an empty domain).
So in my case I import data through csv field one product.template.attribute.value
it will recompute the standard price on all product of my database !

2020-10-14 20:57 UTC, sebastienbeau commented
@mourad-ehm can you check this

2020-10-14 21:58 UTC, legalsylvain requested changes
Hi Seb. Thanks for your work.
i don't get all the changes. remarks inline.

2020-10-14 21:58 UTC, legalsylvain commented on product_standard_margin/models/product_template.py
> +    price_attribute_value_ids = fields.One2many(
Hi. Could you mention where this field is initialized ?

2020-10-14 21:58 UTC, legalsylvain commented on product_standard_margin/models/product_product.py
> +        "product_tmpl_id.price_attribute_value_ids.price_extra",
this field doesn't change the computation of the margin. why did you add it ?

2020-10-14 21:58 UTC, legalsylvain commented on product_standard_margin/models/product_template.py
> +        "list_price",
indeed. Good catch !

2022-08-28 13:29 UTC, legalsylvain commented
ping @sebastienbeau

2023-02-12 12:30 UTC, closed without merging